include: package:very_good_analysis/analysis_options.yaml

linter:

  rules:
    public_member_api_docs: false
    avoid_print: true
    unnecessary_const: true
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true

